# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
general {
	gaps_in = 1
	gaps_out = 2
}

decoration {
	rounding = 20
	dim_inactive = true
	dim_strength = 0.2
	dim_special = 0.07
}

misc {
	disable_hyprland_qtutils_check = true
}
