# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Window size fix
windowrulev2 = size 80% 80%, title:^(Save)(.*)$
windowrulev2 = size 80% 80%, title:^(Open)(.*)$
windowrulev2 = size 80% 80%, title:^(Select)(.*)$
windowrulev2 = maxsize 1300 700, title:^(Open)(.*)$
windowrulev2 = maxsize 1300 700, title:^(Save)(.*)$
windowrulev2 = maxsize 1300 700, title:^(Select)(.*)$
windowrulev2 = move 10% 15%, title:^(Select)(.*)$
windowrulev2 = float, title:^(Select)(.*)$
windowrulev2 = float, title:^(Save)(.*)$
windowrulev2 = float, title:^(Open)(.*)$

windowrulev2 = float, class:^(feh)$
windowrulev2 = move 35% 7%, class:^(feh)$
windowrulev2 = size 60% 90%, class:^(feh)$
